#
# Installs Python3 packages
#
---
- name: Install python3 packages
  become: True
  apt:
    name: "{{ item }}" 
    state: present
    update_cache: True
  loop:
   - "{{ python3_packages }}"


- name: Install python3 pip packages
  pip:
    name: "{{ item }}"
    state: present
    executable: "{{ python_pip_executable }}"
  loop:
    - "{{ python_pip_packages }}"
    - "{{ python_pip_packages_extra }}"